//import { history } from '_helpers';
import Grid from '@mui/material/Grid';
import { OfferCard } from './OfferCard';
import { Box } from '@mui/material';

export { Pricing };

function Pricing() {
    document.title = 'Pricing & Fees';
    return (
        <Box sx={{ mt: 10 }}>
            <Grid
                container
                rowSpacing={1}
                columnSpacing={{ xs: 1, sm: 2, md: 10, lg: 1 }}
                alignContent="center"
            >
                <Grid item md={4}>
                    <OfferCard
                        title="Level 1"
                        description="Explore and play our free drinking game card sets."
                        price="Free"
                        priceDescription="No payment required"
                        perks={['Access to free card sets']}
                    />
                </Grid>
                <Grid item md={4}>
                    <OfferCard
                        title="Level 2"
                        description="Great for players who want to create their own sets."
                        price="50.000 VND"
                        priceDescription="One-time payment"
                        perks={[
                            'Access to premium card sets',
                            'Create customized card sets',
                            'Get unique card sets generated by AI',
                        ]}
                    />
                </Grid>
                <Grid item md={4}>
                    <OfferCard
                        title="Level 3"
                        description="Play with online friends in real time."
                        price="VND"
                        priceDescription="One-time payment"
                        perks={['Real time game hosting']}
                    />
                </Grid>
            </Grid>
        </Box>
    );
}
